version: "3.7"
name: es

services:
  elastic:
    # https://hub.docker.com/_/elasticsearch/
    image: elasticsearch:${ES_VERSION}
    env_file: ./.env
    ports:
      - ${ES_PORT}:9200

  kibana:
    image: kibana:${ES_VERSION}
    env_file: ./.env
    ports:
      - ${KIBANA_PORT}:5601
    depends_on:
      - elastic
